-- The review desk online: what a signed-in reviewer may read and write, and
-- nothing for anyone else.
--
-- The page carries the project's anon key, as every Supabase front end
-- does, whether it is opened from a folder or served from a host. That key
-- is only as private as the policies below make it, so row level security
-- goes on every table first: with no policy for the anon role, the anon key
-- reads nothing. The nightly jobs use the service role, which bypasses RLS,
-- and are unaffected.
--
-- BEFORE RUNNING: the news feed that fills `article` is not this
-- repository's code. If it writes with the anon key rather than the service
-- role, enabling RLS on `article` stops it. Check which key it holds; if it
-- is the anon key, give it the service role key or add an insert policy for
-- it here before running.

alter table public.article            enable row level security;
alter table public.extracted_entities enable row level security;
alter table public.entities           enable row level security;
alter table public.tte_imports        enable row level security;
alter table public.candidate_matches  enable row level security;

-- One row per card, as the card layer builds it, rewritten nightly. The key
-- is the card's own (uid:<record> or new:<type>:<name>), so a card that
-- gains an article keeps its row and its decisions.
create table if not exists public.deck (
  key        text primary key,
  type       text not null,
  entity     text not null,
  card       jsonb not null,
  built_at   timestamptz not null default now()
);
alter table public.deck enable row level security;
drop policy if exists "reviewers read the deck" on public.deck;
create policy "reviewers read the deck" on public.deck
  for select to authenticated using (true);

-- One decision per proposal, written by the page as the reviewer stamps.
-- `decision` is the label the desk keeps in the browser, whole, so the
-- sheets can be rebuilt from the table alone. Whoever decides first keeps
-- it: a second reviewer's decision on the same proposal is refused here,
-- whatever the page believed.
create table if not exists public.reviews (
  id         bigint generated by default as identity primary key,
  pid        bigint not null,
  card_key   text not null,
  reviewer   uuid not null references auth.users (id) on delete cascade,
  verdict    text not null,
  decision   jsonb not null,
  at         timestamptz not null default now(),
  unique (pid)
);
alter table public.reviews drop constraint if exists reviews_pid_reviewer_key;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'reviews_pid_key') then
    alter table public.reviews add constraint reviews_pid_key unique (pid);
  end if;
end $$;
create index if not exists reviews_card_key on public.reviews (card_key);
alter table public.reviews enable row level security;
drop policy if exists "reviewers see every review" on public.reviews;
create policy "reviewers see every review" on public.reviews
  for select to authenticated using (true);
drop policy if exists "reviewers write their own" on public.reviews;
-- A test account may look but not touch: its decisions would otherwise take
-- records from real reviewers for good. The mark is in app_metadata, which
-- only the service role can set; user_metadata the user could edit.
create or replace function public.is_test_account()
returns boolean
language sql
stable
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'test')::boolean, false);
$$;
grant execute on function public.is_test_account() to anon, authenticated, service_role;

create policy "reviewers write their own" on public.reviews
  for insert to authenticated with check (reviewer = auth.uid() and not public.is_test_account());
drop policy if exists "reviewers change their own" on public.reviews;
create policy "reviewers change their own" on public.reviews
  for update to authenticated using (reviewer = auth.uid())
  with check (reviewer = auth.uid() and not public.is_test_account());

-- Who has which card. A card is one reviewer's from the moment it is dealt
-- until they stamp it: no expiry, so nobody is hurried and nothing is ever
-- worked twice. Someone away with a card on their desk keeps it until they
-- return or it is released by hand (python -m src.export --release EMAIL).
create table if not exists public.claims (
  card_key   text primary key,
  reviewer   uuid not null references auth.users (id) on delete cascade,
  claimed_at timestamptz not null default now()
);
alter table public.claims enable row level security;
drop policy if exists "reviewers see claims" on public.claims;
create policy "reviewers see claims" on public.claims
  for select to authenticated using (true);

-- claim_card: free or already mine -> mine, true; held or decided by
-- someone else -> false. The take is one statement, so two reviewers asking
-- for the same card at the same instant cannot both get it: the second
-- insert meets the first's row and changes nothing. Runs as definer so the
-- page needs no write policy on claims and cannot claim in another's name.
create or replace function public.claim_card(key text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or public.is_test_account() then
    return false;
  end if;
  if exists (select 1 from public.reviews where card_key = key and reviewer <> auth.uid()) then
    return false;
  end if;
  insert into public.claims (card_key, reviewer, claimed_at)
  values (key, auth.uid(), now())
  on conflict (card_key) do update set claimed_at = excluded.claimed_at
    where public.claims.reviewer = excluded.reviewer;
  return exists (select 1 from public.claims where card_key = key and reviewer = auth.uid());
end;
$$;

create or replace function public.release_card(key text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.claims where card_key = key and reviewer = auth.uid();
$$;

revoke all on function public.claim_card(text) from public;
revoke all on function public.release_card(text) from public;
grant execute on function public.claim_card(text) to authenticated;
grant execute on function public.release_card(text) to authenticated;

-- Someone without an account asks for one from the sign-in screen. The one
-- thing the anon key may write: a row here, which it cannot read back.
-- Accounts are then created by hand (see the note at the end).
create table if not exists public.access_requests (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text not null,
  message    text,
  asked_at   timestamptz not null default now(),
  handled    boolean not null default false
);
alter table public.access_requests enable row level security;
drop policy if exists "anyone may ask" on public.access_requests;
create policy "anyone may ask" on public.access_requests
  for insert to anon, authenticated
  with check (length(name) between 1 and 120 and length(email) between 3 and 200
              and (message is null or length(message) <= 2000));

-- The policies above only filter rows for a role that already holds the
-- table, and this project does not grant new tables to anyone: without
-- these, every request fails with "permission denied", the nightly publish's
-- included.
grant select, insert, update, delete
  on public.deck, public.reviews, public.claims, public.access_requests to service_role;
grant select on public.deck, public.claims to authenticated;
grant select, insert, update on public.reviews to authenticated;
grant insert on public.access_requests to anon, authenticated;

-- The search index and the NPT map, one JSON file, too large for a table
-- read through the API's 1,000-row page. Private; signed-in reviewers read.
insert into storage.buckets (id, name, public)
values ('desk', 'desk', false)
on conflict (id) do nothing;
drop policy if exists "reviewers read the desk bucket" on storage.objects;
create policy "reviewers read the desk bucket" on storage.objects
  for select to authenticated using (bucket_id = 'desk');

-- Reviewer accounts are created in the dashboard (Authentication > Users >
-- Add user, with "Auto confirm"), and sign-ups are turned off under
-- Authentication > Providers > Email. The display name shown on the desk
-- comes from the user's metadata key "name"; without one, the part of the
-- email before the @ is used. A test account carries {"test": true} in its
-- metadata, and its decisions are left out when decisions are collected.
