-- What the field test needs that the desk did not record.
-- Run after 11_desk_online.sql. Re-runnable.

-- Which model answered. Each job's model chain falls back to a weaker model
-- when a stronger one's daily allowance is spent, so the same night can mix
-- models; the evaluation has to be able to tell them apart.
alter table public.article            add column if not exists relevance_model  text;
alter table public.extracted_entities add column if not exists extraction_model text;
alter table public.candidate_matches  add column if not exists resolution_model text;

-- The evaluation's two logs (docs/evaluation.md): every change a reviewer
-- finds by hand, and each week's minutes and changes, either way of working.
-- A reviewer sees and edits only their own rows; per-person effort is for
-- the evaluation, collected with the service role, not shown to colleagues.
create table if not exists public.change_log (
  id          bigint generated by default as identity primary key,
  reviewer    uuid not null references auth.users (id) on delete cascade,
  method      text not null check (method in ('manual', 'app')),
  article_url text,
  tte_entity  text not null,
  tte_uid     text,
  kind        text not null check (kind in ('new', 'amend')),
  field       text,
  old_value   text,
  new_value   text,
  found_on    date not null default current_date,
  at          timestamptz not null default now()
);

create table if not exists public.weekly_log (
  id          bigint generated by default as identity primary key,
  reviewer    uuid not null references auth.users (id) on delete cascade,
  week_start  date not null,
  method      text not null check (method in ('manual', 'app')),
  minutes     integer not null check (minutes >= 0),
  changes     integer not null check (changes >= 0),
  at          timestamptz not null default now(),
  unique (reviewer, week_start, method)
);

alter table public.change_log enable row level security;
alter table public.weekly_log enable row level security;

drop policy if exists "reviewers keep their own change log" on public.change_log;
create policy "reviewers keep their own change log" on public.change_log
  for all to authenticated
  using (reviewer = auth.uid())
  with check (reviewer = auth.uid() and not public.is_test_account());

drop policy if exists "reviewers keep their own weekly log" on public.weekly_log;
create policy "reviewers keep their own weekly log" on public.weekly_log
  for all to authenticated
  using (reviewer = auth.uid())
  with check (reviewer = auth.uid() and not public.is_test_account());

grant select, insert, update, delete on public.change_log, public.weekly_log to service_role, authenticated;
